[book]
authors = ["agnesLeroy"]
language = "en"
multilingual = false
src = "src"
title = "Concrete-Core Lib"
description = "A guide to help you begin with `concrete-core` !"


[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/concrete/boolean-lib"
git-repository-url = "https://github.com/zama-ai/concrete/tree/master/concrete-core"
theme = "theme"
default-theme = "zama"
google-analytics = "G-XRM93J9QBW"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
